@startuml
skinparam activity {
    ArrowColor green
}

start
:Start OS;

partition "Load Device" {
    fork
        :Start \nTomcat;
        :Load WebZulu;
        repeat
            :Connected \nto ZuluD;
        repeat while (Connected false)
    
    fork again
        :Start \nZuluD;
        repeat
            :Connected \nto DB;
        repeat while (Connected false)
            :Get ports \nsettings;
            :Set ports \nsettings \nin FPGA;
            :Get VLANs \nsettings;
            :Set VLANs \nsettings \nin FPGA;

    fork again
        :Start FPGA;
    
    end fork
}

stop
@enduml