@startuml

title Жизненный цикл \n LoginModule

start

:initialization();
note left
    Подготовка модуля аутентификации.
    Передача параметров для аутентификации пользователя:
    //Subject// - объект аутентификации;
    //CallbackHandler// - обработчик событий;
    //SharedState// - тип аутентификации(логин, отпечаток, ключ и т.д);
    //Options// - опции для данного типа аутентификации.
end note

:login();
note left
    Аутентификаци пользователя. Т.е. непосредственная 
    проверка введеных данных.
    <b>true</b> - аутентификация пройдена;
    <b>false</b> - ошибка аутентификации.
end note

if (auth) then (succeeded)
    :commit();
    note left
        Сообщает в объект (//Subject//)
        информацию о пользователе в зависимости
        от метода и ОС.
    end note
else (failed)
    :aborted();
    note right
        Освобождает все ресурсы.
    end note
endif

stop

@enduml
