@startuml

title <b><size:45>Usercase Diagram</size></b>

skinparam usecase {
	BackgroundColor #6CFFAE
	BorderColor Black

	BackgroundColor<<Telnet client>> #73A0DC
	BackgroundColor<<SNMP client>> #73A0DC
	BackgroundColor<<SSH client>> #73A0DC
	BackgroundColor<<Site>> #73A0DC

	BackgroundColor<<Telnet server>> YellowGreen
	BackgroundColor<<SNMP server>> YellowGreen
	BackgroundColor<<SSH server>> YellowGreen
	BackgroundColor<<Application server>> YellowGreen
	
	BackgroundColor<<Control plane>> #D2FFDC
	BackgroundColor<<Data plane>> #D2FFDC
	
	ArrowColor Green
	ArrowFontName Impact
	ArrowFontColor #777777
}

skinparam cloud {
	BackgroundColor White
	BorderColor Black
}


User << User >>
(SNMP) << SNMP client >> as SNMPc
(SSH) << SSH client >> as SSHc
(Telnet) << Telnet client >> as Telnetc
(Web) << Site >>

(SNMP) << SNMP server >> as SNMPs
(SSH) << SSH server >> as SSHs
(Telnet) << Telnet server >> as Telnets
(Tomcat) << Application server >>

cloud "Data bus" as D_Bus

(Messages) << Controller messages >>

(Managment) << Managment plane >>
(Kernel) << Kernel space >>
(Storage) << Storage disk >>
(ZULU) << Control daemon >>

(Control) << Control plane >>
(Data) << Data plane >>



User --> (SNMPc)
User --> (SSHc)
User --> (Telnetc)
User --> (Web)

(SNMPc) <--> (SNMPs) : Socket
(SSHc) <--> (SSHs) : Socket
(Telnetc) <--> (Telnets) : Socket
(Web) <--> (Tomcat) : RPC

(SNMPs) .(0). D_Bus
(SSHs) .(0). D_Bus
(Telnets) .(0). D_Bus
(Tomcat) .(0). D_Bus

D_Bus .(0). (Messages)

(Messages) <--> (ZULU)
(Messages) <--> (Managment)

(Managment) <--> (Kernel)
(Managment) <--> (Storage)

(ZULU) <--> (Control) : I2C
(Control) <--> (Data)


@enduml
