@startuml

skinparam activity {
    ArrowColor green
}

start

:Аутентификация;
note left
    Запрос 
    MessageUser
end note

if (Сессия новая?) then (Да)
    :Новая сессия;
    :Страница \nавторизации;
else (Нет)
    -[#red]->
    :Есть информация \nо сесии;
    if (Пользователь \nавторизован?) then (Да)
        :Достать информацию \nо пользователе;
    else (Нет)
        -[#red]->
        :Достать информацию \nо местонахождении;
    endif
    :Отправить информацию \nклиенту;
endif
stop

@enduml