@startuml
salt
{{T
+
++ Monitoring ( Телеметрия )
+++ MonitoringStatusPorts ( Статусы портов )
+++ MonitoringStatisticsPorts ( Статистика портов )
+++ MonitoringUsePorts ( Использование портов )
+++ MonitoringSwitchHealth ( Железо )
+++ MonitoringLogs ( Системный журнал )
++ Systems ( Система )
+++ SystemsSettings ( Системные настройки )
+++ SystemsInstallation ( Экспресс установка )
+++ SystemsLogs ( Системный журнал )
+++ SystemsSNTP ( Настройка времени )
++ Interface ( Интерфейсы )
+++ InterfaceEthernet ( Ethernet )
++++ InterfaceEthernetList ( Таблица Ethernet интерфейсов )
++++ InterfaceEthernetAdd ( Добавить Ethernet интерфейс )
++++ InterfaceEthernetEdit ( Редактировать Ethernet интерфейс )
+++ InterfaceTCP ( TCP )
+++ InterfaceIPv4 ( IPv4 )
+++ InterfaceToS ( ToS )
+++ InterfaceMPLS ( MPLS )
+++ InterfaceBGP4 ( BGP-4 )
+++ InterfaceVLAN ( VLAN )
++++ InterfaceVLANList ( Таблица VLAN )
++++ InterfaceVLANAdd ( Добавить VLAN )
++++ InterfaceVLANEdit ( Редактированть VLAN )
++ Mirroring ( Зеркалирование )
++ Firewall ( Межсетевой экран )
+++ FirewallICMP ( ICMP )
++ NAT ( NAT )
++ Security ( Безопастность )
+++ SecurityTrustedHost ( Доверенный хост )
+++ SecurityPorts ( Безопастность портов )
+++ SecurityTelnet ( Telnet )
+++ SecurityARP ( ARP )
++++ SecurityARPList ( Таблица ARP )
++++ SecurityARPAdd ( Добавить ARP )
++++ SecurityARPEdit ( Редактировать ARP )
+++ SecurityMAC ( Таблица MAC )
+++ SecurityIP ( IP группы )
++ UserGroup ( Пользователи )
+++ Users ( Пользователи )
++++ UserList ( Таблица пользователей )
++++ UserAdd ( Добавление пользователя )
++++ UserEdit ( Редактирование пользователя )
+++ Groups ( Группы и разрешения )
++++ GroupList ( Таблица групп )
++++ GroupAdd ( Добавление группы )
++++ GroupEdit ( Редактирование группы )
++ Tools ( Инструменты )
+++ ToolsReboot ( Перезапуск )
+++ ToolsReset ( Сброс )
+++ ToolsBackup ( Восстановление и резервное копирование настроек )
+++ ToolsUpdate ( Обновление и резервное копирование ПО )
++ Help (Сетевой помошник)
}}
@enduml