@startuml

package ru.zulu.client.messages {
}

package ru.zulu.client.messages.system {
}

package ru.zulu.client.messages.txrx {
}

package ru.zulu.client.messages.types {
}

package ru.zulu.client.panels {
}

package ru.zulu.client.utils {
}

@enduml